# Generated by Django 5.2.5 on 2025-08-15 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_description_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Depod Haqqında', max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('story', models.TextField(blank=True)),
                ('experience_years', models.PositiveIntegerField(default=5)),
                ('product_models', models.PositiveIntegerField(default=15)),
                ('happy_customers', models.PositiveIntegerField(default=10000)),
                ('quality_rating', models.CharField(default='99%', max_length=10)),
                ('mission', models.TextField(blank=True)),
                ('vision', models.TextField(blank=True)),
                ('values', models.JSONField(blank=True, default=list, help_text='List of value dicts: {icon, title, text}')),
                ('team', models.JSONField(blank=True, default=list, help_text='List of team dicts: {title, description, detail}')),
                ('technology_title', models.CharField(default='Texnologiya və İnnovasiya', max_length=200)),
                ('technology_text', models.TextField(blank=True)),
                ('technology_features', models.JSONField(blank=True, default=list, help_text='List of feature strings')),
                ('technology_stats', models.JSONField(blank=True, default=list, help_text='List of stat dicts: {number, label}')),
                ('contact_title', models.CharField(default='Bizimlə Əlaqə Saxlayın', max_length=200)),
                ('contact_text', models.TextField(blank=True)),
                ('footer_description', models.TextField(blank=True)),
                ('footer_email', models.CharField(blank=True, max_length=100)),
                ('footer_phone', models.CharField(blank=True, max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Pages',
            },
        ),
    ]
