# Generated by Django 5.2.5 on 2025-08-15 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_aboutpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='team_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='values_title',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='team',
            field=models.JSONField(blank=True, default=list, editable=False, help_text='Deprecated: use AboutTeamMember inlines'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='technology_features',
            field=models.JSONField(blank=True, default=list, editable=False, help_text='Deprecated: use AboutTechFeature inlines'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='technology_stats',
            field=models.JSONField(blank=True, default=list, editable=False, help_text='Deprecated: use AboutTechStat inlines'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='values',
            field=models.JSONField(blank=True, default=list, editable=False, help_text='Deprecated: use AboutValue inlines'),
        ),
        migrations.CreateModel(
            name='AboutTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('detail', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_items', to='catalog.aboutpage')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AboutTechFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_items', to='catalog.aboutpage')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AboutTechStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_stat_items', to='catalog.aboutpage')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AboutValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, choices=[('fa-solid fa-gem', 'Gem (Keyfiyyət)'), ('fas fa-rocket', 'Rocket (İnnovasiya)'), ('fa-solid fa-handshake', 'Handshake (Güvən)'), ('fas fa-bolt', 'Bolt (Sürət)'), ('fa-solid fa-chevron-up', 'Chevron Up (Davamlı İnkişaf)'), ('fa-solid fa-trophy', 'Trophy (Mükəmməllik)')], max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values_items', to='catalog.aboutpage')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
