# Generated by Django 5.2.5 on 2025-08-15 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_aboutpage_team_description_aboutpage_values_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Saytda göstəriləcək aktiv səhifə'),
        ),
        migrations.AddConstraint(
            model_name='aboutpage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='uniq_active_aboutpage'),
        ),
    ]
