# Generated by Django 5.2.5 on 2025-08-15 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_aboutpage_is_active_aboutpage_uniq_active_aboutpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Bizimlə Əlaqə Saxlayın', max_length=200)),
                ('hero_subtitle', models.CharField(blank=True, default='Sizin suallarınız bizim üçün önəmlidir', max_length=300)),
                ('email_primary', models.CharField(blank=True, default='info@depod.az', max_length=150)),
                ('email_secondary', models.CharField(blank=True, default='support@depod.az', max_length=150)),
                ('phone_primary', models.CharField(blank=True, default='+994 12 XXX XX XX', max_length=50)),
                ('phone_secondary', models.CharField(blank=True, default='+994 50 XXX XX XX', max_length=50)),
                ('address_line1', models.CharField(blank=True, default='Bakı şəhəri', max_length=200)),
                ('address_line2', models.CharField(blank=True, default='Azərbaycan', max_length=200)),
                ('form_title', models.CharField(default='Bizimlə Əlaqə Forma', max_length=200)),
                ('form_text', models.TextField(blank=True, default='Suallarınızı, təklif və şikayətlərinizi bizə göndərin. Sizinlə qısa zamanda əlaqə saxlayacağıq.')),
                ('support_title', models.CharField(default='Sürətli Dəstək', max_length=200)),
                ('support_text', models.TextField(blank=True, default='Təcili suallarınız üçün birbaşa bizim dəstək komandamızla əlaqə saxlayın.')),
                ('support_phone', models.CharField(blank=True, default='+994 XX XXX XX XX', max_length=50)),
                ('catalog_title', models.CharField(default='Məhsul Kataloqu', max_length=200)),
                ('catalog_text', models.TextField(blank=True, default='Məhsullarımız haqqında ətraflı məlumat əldə edin.')),
                ('catalog_link', models.CharField(blank=True, default='index.html#products', max_length=300)),
                ('map_section_title', models.CharField(default='Məkanımız', max_length=200)),
                ('map_heading', models.CharField(default='Depod Ofisi', max_length=200)),
                ('map_address', models.CharField(default='Bakı şəhəri, Azərbaycan', max_length=300)),
                ('map_button_text', models.CharField(default='Xəritədə Aç', max_length=100)),
                ('map_url', models.CharField(blank=True, default='', max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False, help_text='Saytda göstəriləcək aktiv əlaqə səhifəsi')),
            ],
            options={
                'verbose_name': 'Contact Page',
                'verbose_name_plural': 'Contact Pages',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='uniq_active_contactpage')],
            },
        ),
        migrations.CreateModel(
            name='ContactFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='catalog.contactpage')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContactWorkingHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='catalog.contactpage')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
