# Generated by Django 5.2.5 on 2025-08-15 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_contactpage_contactfaq_contactworkinghour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='footer_description',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='footer_email',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='footer_phone',
        ),
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='Keyfiyyətli texnoloji məhsullar istehsalçısı. Yenilikçi həllər və etibarlı məhsullarla sizin xidmətinizdəyik.')),
                ('email', models.CharField(blank=True, default='info@depod.az', max_length=100)),
                ('phone', models.CharField(blank=True, default='+994 XX XXX XX XX', max_length=50)),
                ('bottom_text', models.CharField(blank=True, default='© 2025 Depod. Bütün hüquqlar qorunur.', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False, help_text='Saytda göstəriləcək aktiv footer')),
            ],
            options={
                'verbose_name': 'Footer Settings',
                'verbose_name_plural': 'Footer Settings',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='uniq_active_footer')],
            },
        ),
    ]
