# Generated by Django 5.2.5 on 2025-08-15 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_remove_aboutpage_footer_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.SlugField(editable=False, help_text='Auto-generated from name (e.g., peak-black)', max_length=100, primary_key=True, serialize=False),
        ),
    ]
