# Generated by Django 5.2.5 on 2025-08-20 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=100, verbose_name='Soyad')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefon nömrəsi')),
                ('city', models.CharField(choices=[('baku', 'Bakı'), ('ganja', 'Gəncə'), ('sumqayit', 'Sumqayıt'), ('mingachevir', 'Mingəçevir'), ('quba', 'Quba'), ('lankaran', 'Lənkəran'), ('shaki', 'Şəki'), ('yevlax', 'Yevlax'), ('nakhchivan', 'Naxçıvan'), ('ordubad', 'Ordubad'), ('qabala', 'Qəbələ'), ('qusar', 'Qusar'), ('shamakhi', 'Şamaxı'), ('tovuz', 'Tovuz'), ('agdam', 'Ağdam'), ('barda', 'Bərdə'), ('beylagan', 'Beyləqan'), ('bilasuvar', 'Biləsuvar'), ('dashkasan', 'Daşkəsən'), ('fizuli', 'Füzuli'), ('gadabay', 'Gədəbəy'), ('goranboy', 'Goranboy'), ('goychay', 'Göyçay'), ('hajigabul', 'Hacıqabul'), ('imishli', 'İmişli'), ('ismayilli', 'İsmayıllı'), ('kalbajar', 'Kəlbəcər'), ('kurdamir', 'Kürdəmir'), ('lachin', 'Laçın'), ('lerik', 'Lerik'), ('masalli', 'Masallı'), ('neftchala', 'Neftçala'), ('oguz', 'Oğuz'), ('qakh', 'Qax'), ('qazakh', 'Qazax'), ('qobustan', 'Qobustan'), ('salyan', 'Salyan'), ('shamkir', 'Şəmkir'), ('shusha', 'Şuşa'), ('tartar', 'Tərtər'), ('ujar', 'Ucar'), ('xankendi', 'Xankəndi'), ('yardimli', 'Yardımlı'), ('zangilan', 'Zəngilan'), ('zaqatala', 'Zaqatala'), ('zardab', 'Zərdab')], max_length=50, verbose_name='Şəhər')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email (İstəyə görə)')),
                ('offer_text', models.TextField(verbose_name='Təklif mətn')),
                ('status', models.CharField(choices=[('pending', 'Gözləyir'), ('reviewed', 'Baxılıb'), ('accepted', 'Qəbul edilib'), ('rejected', 'Rədd edilib')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Məhsul Təklifi',
                'verbose_name_plural': 'Məhsul Təklifləri',
                'ordering': ['-created_at'],
            },
        ),
    ]
