# Generated by Django 5.2.5 on 2025-08-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_productoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoffer',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Miqdar (ədəd)'),
        ),
        migrations.AlterField(
            model_name='productoffer',
            name='offer_text',
            field=models.TextField(blank=True, verbose_name='Təklif mətn (istəyə görə)'),
        ),
    ]
