# Generated by Django 5.2.5 on 2025-08-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_contactmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpage',
            options={'verbose_name': 'Haqqında Səhifəsi', 'verbose_name_plural': 'Haqqında Səhifəsi'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kateqoriya', 'verbose_name_plural': 'Kateqoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='contactpage',
            options={'verbose_name': 'Əlaqə Səhifəsi', 'verbose_name_plural': 'Əlaqə Səhifəsi'},
        ),
        migrations.AlterModelOptions(
            name='footersettings',
            options={'verbose_name': 'Footer Hissəsi', 'verbose_name_plural': 'Footer Hissəsi'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Məhsul', 'verbose_name_plural': 'Məhsullar'},
        ),
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sayt Ziyarəti',
                'verbose_name_plural': 'Sayt Ziyarətləri',
                'indexes': [models.Index(fields=['date'], name='catalog_sit_date_29743a_idx'), models.Index(fields=['session_key'], name='catalog_sit_session_d00beb_idx')],
                'unique_together': {('date', 'session_key')},
            },
        ),
    ]
