services:
  - type: web
    name: depod-api
    runtime: python
    plan: free
    rootDir: backend
  buildCommand: pip install -r requirements-render.txt && python manage.py collectstatic --noinput
  startCommand: python manage.py migrate --noinput && python manage.py ensure_superuser && gunicorn core.wsgi:application --bind 0.0.0.0:$PORT
  healthCheckPath: /healthz
  envVars:
      # Connect Django to Render Postgres via a single URL
      - key: DATABASE_URL
        fromDatabase:
          name: depod-db
          property: connectionString

      # App configuration
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: DJANGO_ALLOWED_HOSTS
        value: .onrender.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://*.onrender.com
      - key: DJANGO_SERVE_MEDIA
        value: true
      - key: CORS_ALLOW_ALL
        value: true
      # Email credentials (prompt on first deploy; do not commit secrets)
      - key: DJANGO_EMAIL_BACKEND
        value: django.core.mail.backends.smtp.EmailBackend
      - key: EMAIL_HOST
        sync: false
      - key: EMAIL_PORT
        sync: false
      services:
        - type: web
          name: depod-api
          runtime: python
          plan: free
          rootDir: backend
          buildCommand: pip install -r requirements-render.txt && python manage.py collectstatic --noinput
          startCommand: python manage.py migrate --noinput && python manage.py ensure_superuser && gunicorn core.wsgi:application --bind 0.0.0.0:$PORT
          healthCheckPath: /healthz
          envVars:
            # Connect Django to Render Postgres via a single URL
            - key: DATABASE_URL
              fromDatabase:
                name: depod-db
                property: connectionString
            # App configuration
            - key: DJANGO_SECRET_KEY
              generateValue: true
            - key: DJANGO_DEBUG
              value: false
            - key: DJANGO_ALLOWED_HOSTS
              value: .onrender.com
            - key: CSRF_TRUSTED_ORIGINS
              value: https://*.onrender.com
            - key: DJANGO_SERVE_MEDIA
              value: true
            - key: CORS_ALLOW_ALL
              value: true
            # Email credentials (prompt on first deploy; do not commit secrets)
            - key: DJANGO_EMAIL_BACKEND
              value: django.core.mail.backends.smtp.EmailBackend
            - key: EMAIL_HOST
              sync: false
            - key: EMAIL_PORT
              sync: false
            - key: EMAIL_HOST_USER
              sync: false
            - key: EMAIL_HOST_PASSWORD
              sync: false
            - key: EMAIL_USE_TLS
              value: true
            - key: EMAIL_USE_SSL
              value: false
            - key: DEFAULT_FROM_EMAIL
              sync: false
            - key: SERVER_EMAIL
              sync: false
            - key: DEFAULT_NOTIFY_EMAIL
              sync: false
            # Telegram notifications
            - key: TELEGRAM_BOT_TOKEN
              sync: false
            - key: TELEGRAM_CHAT_ID
              sync: false
            # Optional: initial admin (Render will prompt once at first deploy)
            - key: DJANGO_SUPERUSER_USERNAME
              sync: false
            - key: DJANGO_SUPERUSER_EMAIL
              sync: false
            - key: DJANGO_SUPERUSER_PASSWORD
              sync: false
      databases:
        - name: depod-db
          plan: free
