version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-depod}
      POSTGRES_USER: ${POSTGRES_USER:-depod}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-depod}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    build: .
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    environment:
      DJANGO_ALLOWED_HOSTS: "*"
      CORS_ALLOW_ALL: "true"
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  pgdata:
